openapi: 3.0.1
info:
  title: IndieFoods
  description: Backend for IndieFoods
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Auth
    description: Authentication endpoints
paths:
  /auth/signup-user:
    post:
      summary: Signup a new user
      description: Signup a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupUser'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupUserResponse'
  /auth/signup-chef:
    post:
      summary: Signup a new chef
      description: Signup a new chef
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupChef'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupChefResponse'
components:
  schemas:
    SignupUser:
      type: object
      required:
        - name
        - phone
        - address
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          type: array
          items:
            type: object
            properties:
              address:
                type: string
              pincode:
                type: string
        email:
          type: string
    SignupUserResponse:
      type: object
      properties:
        message:
          type: string
    SignupChef:
      type: object
      required:
        - name
        - phone
        - address
        - fssaiId
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          type: array
          items:
            type: object
            properties:
              address:
                type: string
              pincode:
                type: string
        fssaiId:
          type: string
        email:
          type: string
    SignupChefResponse:
      type: object
      properties:
        message:
          type: string